yandex map
stayyoungugly/tinkoff-project-2022 pull request #14
Opened 2022-05-07 07:53 UTC by stayyoungugly

2022-05-07 09:36 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/domain/usecase/network/CheckInternetUseCase.kt
> +        if (connectivityManager != null) {
Чтобы избежать вложенности можно писать 
`if (connectivityManager == null) return`
Хотя это дело вкуса

2022-05-07 09:36 UTC, Mexator commented on build.gradle
> +        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.5.0-beta01"
Будет надежнее стабильную версию использовать

2022-05-09 19:19 UTC, Mexator requested changes

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        mapCity.isIndoorEnabled = true
Не забывайте про let, apply, with и иже с ними
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    private lateinit var mapView: MapView
Почти всегда, когда у тебя есть методы initXXX(), где ты просто создаешь объект, есть смысл заменить такие создания на проперти-делегаты.

Например, так можно сократить код создания вьюмодели
```kotlin
private val mapViewModel by viewModels<MapViewModel> {
        AuthFactory(
            UserAuthContainer,
            UserTokenContainer(sharedPreferences)
        )
    }
```

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    private fun checkPermission() {
Может вынести логику работы с пермишшнами во вьюмодель?

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    private var followUserLocation = false
Проверь, что все переменные действительно должны быть полями, и их нельзя сделать локальными

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        }
Неиспользуемый код. Пробегайся по файлам перед тем как их на ревью кидать. Бывает полезно

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +                CameraPosition(Point(location.latitude, location.longitude), 18.0f, 0.0f, 0.0f),
Какая-то волшебная константа 18.0f. Надо бы ее вынести в companion object

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        userLocationView.accuracyCircle.fillColor = Color.LTGRAY and -0x66000001
Тут тоже какие-то непонятные константы :(

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    private val geoObjectTapListener =
Лучше все поля вверху класса держать

2022-05-09 19:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        GeoObjectTapListener { event ->
Подумайте о том, чтобы на подписки и лайвдаты переписать этот фрагмент. Очень тяжело понять, что происходит (я не понял)

2022-05-09 19:19 UTC, Mexator commented on app/src/main/res/values/strings.xml
> +    <string name="textview">TextView</string>
Как будто удалить забыл

2022-05-09 19:19 UTC, Mexator commented
Кстати, в ресурсах картинки неиспользуемые

2022-05-11 23:16 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    private var followUserLocation = false
проверил, по-моему, действительно должны быть полями

2022-05-11 23:16 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        }
я пока оставил, потом как разберусь с получением рабочих ссылок буду использовать

2022-05-12 01:12 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        GeoObjectTapListener { event ->
переписал немного, это просто всё объекты из библиотеки yandex map и они просят реализовывать используемые листнеры

2022-05-14 09:56 UTC, Mexator approved these changes

2022-05-14 09:56 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
>          sharedPreferences = activity?.getPreferences(Context.MODE_PRIVATE) ?: return
1. requireActivity()
2. Переместить в lazy-блок

2022-05-14 09:56 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +//            ну я потом этот код буду использовать, ладно уж
Ну ладно

2022-05-22 16:05 UTC, merged