Feature/firestore
stayyoungugly/tinkoff-project-2022 pull request #15
Opened 2022-05-24 09:21 UTC by OlgaMartazova

2022-05-25 07:08 UTC, Mexator requested changes

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/database/remote/Firestore.kt
> +        var user: User?
Зачем эта переменная, можно ж без неё

```kotlin
return await(dockRef.get()).toObject<User>()
```

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/impl/UserRepositoryImpl.kt
> +) : UserRepository {
Почему va**r**?

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/mapper/UserEntityMapper.kt
> +            UserEntity(
А когда может быть такое, что firestore вернет док с пустыми полями?

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/response/User.kt
> +data class User(
Название немного путает, на первый взгляд кажется, что это domain entity. Назвать бы это `UserResponse`...

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/domain/entity/UserEntity.kt
> +data class UserEntity (
А вот это наоборот бы в `User` переименовать, потому что с суффиксом Entity обычно называют классы, которые в Room кладут

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/domain/usecase/user/AddUserUseCase.kt
> +    private val dispatcher: CoroutineDispatcher = Dispatchers.Main
Если везде диспатчер передается явно, зачем дефолтный параметр? Тем более, с ним будет краш с NetworkOnMainThreadException

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/domain/usecase/user/GetUserByNicknameUseCase.kt
> +    private val dispatcher: CoroutineDispatcher = Dispatchers.Main
То же самое, что писал выше про диспатчер

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/SignInFragment.kt
> +            tiNickname.visibility = View.GONE
Выглядит как костыль. Если прихдится так делать, значит надо вынести не-общие поля из общей разметки и добавить туда, где они нужны

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/SignUpFragment.kt
Если вынести валидацию во вьюмодель, то эти поля будут не нужны

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/viewmodel/SignUpViewModel.kt
> +    private var _nicknameExist: MutableLiveData<Boolean> = MutableLiveData()
Название вводит в заблуждение, потому что `true` означает, что ник свободен

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/SignUpFragment.kt
> +        with(binding) {
Валидацию надо вынести во вьюмодель. В идеале, у нее должен быть только один метод - onRegisterClicked(name: String, surname: String, ...).

Наружу из VM должна торчать лайвдата с ошибкой/успехом, это можно сделать через sealed class. 

Фрагмент должен подписываться на эту лайвдату и показывать ошибку/навигировать дальше. Еще он должен прокидывать клики и занчения полей в метод VM.

2022-05-25 07:08 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/SignUpFragment.kt
> +        with(binding) {
В принципе, до этого было +- правильно, но есть "лишние" методы onSaveTokenClick и addNewUser

2022-05-25 21:13 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/data/mapper/UserEntityMapper.kt
> +            UserEntity(
firestore требует, чтобы объект, в который десериализуется запись, содержал no-arguments constructor, умные люди в интернете сказали, что это значит, что дата-класс должен быть с нуллабельными полями и дефолтными значениями, только после этого возможна десериализация. поэтому у нас есть класс User (будет UserResponse), который мы отдаем в firestore и который забираем из firestore, и класс UserEntity (будет User), который уже обычный дата-класс без нуллабельных полей и дефолтных значений, в него мы мапим UserResponse.

2022-05-27 14:03 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/mapper/UserEntityMapper.kt
> +            UserEntity(
gson номер 2, лол

2022-05-27 14:09 UTC, Mexator approved these changes

2022-05-31 12:42 UTC, closed without merging