add review to firestore
stayyoungugly/tinkoff-project-2022 pull request #17
Opened 2022-05-25 02:56 UTC by stayyoungugly

небольшое пояснение - решил не хранить информацию о месте в бд, потому что у любого места на яндекс карте есть uri, по которому можно вытаскивать всю необходимую информацию, его собственно и храню.

2022-05-25 07:24 UTC, Mexator requested changes

2022-05-25 07:24 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/data/database/remote/Firestore.kt
> +        var reviews = ArrayList<Review>()
Уже писал выше про лишние переменные в запросах к firestore

2022-05-25 07:24 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        val uri = response.collection.children.firstOrNull()?.obj
Может, этот response прокинуть в VM, а она там уж сама решит как обновить экран?

2022-05-25 07:24 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/viewmodel/MapViewModel.kt
> +    private var _reviewAdded: MutableLiveData<Boolean> = MutableLiveData()
Тут va**r** не нужен

2022-05-27 01:14 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/viewmodel/MapViewModel.kt
> +    private var _reviewAdded: MutableLiveData<Boolean> = MutableLiveData()
правильно понимаю, что вообще нигде вар не нужен во вьюмоделях?

2022-05-27 02:11 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        val uri = response.collection.children.firstOrNull()?.obj
не очень понял конкретно этот коммент, просто перенес весь процесс поиска в vm

2022-05-27 14:16 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        val uri = response.collection.children.firstOrNull()?.obj
Норм, я почему-то подумал, что фрагмент обязательно должен реализовывать этот листенер

2022-05-27 14:16 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/viewmodel/MapViewModel.kt
> +    private var _reviewAdded: MutableLiveData<Boolean> = MutableLiveData()
У VM может быть внутреннее состояние, которое надо проверять по клику кнопки, например. Оно может быть var. Но наружу торчать должны только лайвдаты/флоу/rx observable. Суть паттерна в этом: ты уведомляешь VM о событиях через вызовы ее методов, и получаешь обновления UI через подписки. Сделано так, чтобы VM не хранила ссылок на View.

2022-05-27 14:17 UTC, Mexator approved these changes

2022-05-27 14:25 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/viewmodel/MapViewModel.kt
> +    private var _reviewAdded: MutableLiveData<Boolean> = MutableLiveData()
понял

2022-06-01 08:19 UTC, Mexator approved these changes

2022-06-01 08:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +        mapCity.addInputListener(listener)
Разве диалог не закрывается сам, если тапнуть вне него? Мне кажется, эта штука не нужна

2022-06-01 08:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/BottomSheetFragment.kt
> +    fun changeStateToHidden() {
Зачем эти два метода? Не нашел использований

2022-06-01 08:19 UTC, Mexator commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    }
Классно сделал с общей вьюмоделью 👍🏻

2022-06-01 15:58 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/BottomSheetFragment.kt
> +    fun changeStateToHidden() {
я кстати не понял, почему-то у меня не получилось вызвать эти два метода у фрагмента из MapFragment, хотя они публичные и должны вызываться..

2022-06-02 06:57 UTC, stayyoungugly commented on app/src/main/java/com/itis/springpractice/presentation/ui/fragment/MapFragment.kt
> +    }
это в итоге вообще не работает(

2022-06-03 20:20 UTC, merged